pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven { url "https://jitpack.io" }
        maven {url 'https://developer.huawei.com/repo/'}
        maven {
            url "https://maven.google.com"
        }
    }
}
rootProject.name = "TsddClient"
include ':MyLibs:rlottie'
// HUAWEI 分支不编译其他厂商推送模块。
// include ':MyLibs:oppopush'
// include ':MyLibs:vivopush'
// include ':MyLibs:honorpush'
include ':app'
include ':wkbase'
include ':wkuikit'
include ':wkscan'
include ':wklogin'
include ':wkpush'
include ':wkflagship'
include ':wkvideo'
include ':wkmoments'
include ':wksticker'
include ':wkrtc'

